task3 done
riapush/Computer-graphics-course pull request #3
Opened 2024-02-23 19:31 UTC by riapush

2024-02-25 10:27 UTC, anthark requested changes
У меня появились два помощника, работающих на зачет по педпрактике =) Ваши работы будет проверять https://github.com/Sairsey. Добавьте его, пожалуйста =)

2024-02-25 17:03 UTC, riapush commented
добавила, жду, когда инвайт примут

2024-02-26 12:14 UTC, Sairsey commented
Добрый день!

2024-02-26 12:16 UTC, Sairsey commented
Из необязательного, но очень желательного - удалите пожалуйста из репозитория Computer_graphics.vcxproj.FileListAbsolute.txt и Computer_graphics.vcxproj.user
в них нет никакой нужды =)

2024-02-26 12:25 UTC, Sairsey commented
Знаете, ваш код и ошибки очень похожи на те, что я увидел у @iMaanick. 
Не знаю в чем тут дело, но надеюсь в будущем я такого не увижу =)

2024-02-26 12:26 UTC, Sairsey requested changes

2024-02-26 12:26 UTC, Sairsey commented on Computer_graphics/Computer_graphics/main.cpp
>      return TRUE;
В данной ситуации стоит использовать S_OK, потому что HRESULT требует константы из другого набора

2024-02-26 12:26 UTC, Sairsey commented on Computer_graphics/Computer_graphics/input.cpp
> +    hr = DirectInput8Create(hinst, DIRECTINPUT_VERSION, IID_IDirectInput8, (void**)&m_directInput, NULL);
Не самый удачный выбор API для работы с устройствами ввода.
У меня под отладчиком Visual Stuido метод Acquire возвращает ошибку доступа. 
Предлагаю воспользоваться WinAPI функциями GetCursorPos и GetKeyboardState

2024-02-26 17:44 UTC, Sairsey commented
Лабораторная зачтена, но прошу учесть мои комментарии.
В следующих лабораторных я не буду принимать Direct8Input.

2024-02-26 17:44 UTC, merged