added last task
riapush/Computer-graphics-course pull request #8
Opened 2024-04-11 16:34 UTC by riapush

2024-04-12 14:59 UTC, Sairsey requested changes
Добрый день. Добавьте режим отладки как в лабораторной 7.

2024-04-15 08:25 UTC, Sairsey requested changes

2024-04-15 08:25 UTC, Sairsey commented on Computer_graphics/defines.hlsli
> +#define MAX_CUBES 400
Давайте поднимем это число до 1000

2024-04-15 08:25 UTC, Sairsey commented on Computer_graphics/renderer.cpp
> +    tmp.pos = XMFLOAT4((float)(rand() % 10 - i % 15), (float)(rand() % 10 - i % 15), (float)(rand() % 10 - i % 15), (float)(rand() % 6 - 3));
Какая-то странная генерация позиций. Лучше используется алгоритм генерации псевдослучайного дробного числа в диапазоне.

2024-04-15 08:25 UTC, Sairsey commented on Computer_graphics/renderer.h
> +constexpr const int maxCubeNumber = 400;
Строго говоря, вы подключаете здесь defines.hlsli в котором уже объявили эту константу. Давайте не будем дублировать значения лишний раз?

2024-04-15 09:03 UTC, Sairsey commented
Ну и у вас есть всё необходимое чтобы посчитать сколько времени экономит каждая техника которую вы прошли в рамках курса. Давайте найдем с вами то число кубов, при котором GPU Culling и Instancing имеют смысл. Для этого

1) Возьмите лабораторные 6, 7 и 9. Сделайте так, чтобы они выводили одно и то же, используя они и те же шейдеры (возможно какую-то функциональность надо будет отключить). Т.е. различались только способом отрисовки кубиков.
2) Добавьте в каждую замер времени - сколько миллисекунд требуется на выполнение Renderer::render и Renderer::getState (при помощи std::chrono).
3) Запустите с разными параметрами и разным числом кубов например 10, 100, 1000, 10000, 100000. Замеры представьте в графиком и пришлите мне его сюда.

2024-04-15 09:18 UTC, Sairsey commented
Я понимаю что задание непростое, поэтому сдвину дедлайн по нему до 19-ого числа

2024-04-16 09:12 UTC, riapush commented
Отключила фрустум, усредняла по 300 значениям.
![image](https://github.com/riapush/Computer-graphics-course/assets/76725077/faa09f02-c8b5-4f53-9bb2-dddb21d6f04b)
![image](https://github.com/riapush/Computer-graphics-course/assets/76725077/0081840c-e472-41ee-b75e-6bc3eaa6861a)

2024-04-16 19:02 UTC, Sairsey commented
Принято!

2024-04-16 19:02 UTC, Sairsey approved these changes

2024-04-16 19:02 UTC, merged